apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-service
spec:
  selector:
    matchLabels:
      app: api-service
  replicas: 1
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: api-service
          ports:
            - name: api-service
              containerPort: 3000
          imagePullPolicy: Never 

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-service
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer 