apiVersion: apps/v1
kind: Deployment
metadata:
  name: coindesk-deployment
  labels:
    app: coindesk
spec:
  selector:
    matchLabels:
      app: coindesk
  replicas: 1
  template:
    metadata:
      labels:
        app: coindesk
    spec:
      containers:
        - name: coindesk
          image: coindesk
          ports:
            - name: coindesk
              containerPort: 9000
          imagePullPolicy: Never 


---
apiVersion: v1
kind: Service
metadata:
  name: coindesk
spec:
  selector:
    app: coindesk
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  type: ClusterIP
